require('joe.core.plugin_configs.nvim-tree')
require('joe.core.plugin_configs.lualine')
require('joe.core.plugin_configs.dracula')
require('joe.core.plugin_configs.treesitter')
require('joe.core.plugin_configs.telescope')
require('joe.core.plugin_configs.claude')
